import type { CampaignConfig } from '../src/types';

// Premios compartidos entre todos los proyectos (puedes personalizarlos por plaza abajo)
const premiosBase = [
  { texto: 'Tu reserva vale x20', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x20.png' },
  { texto: '$500 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/500-dscto-adicional.png' },
  { texto: 'Tu reserva vale x10', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x10.png' },
  { texto: '+2% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/2-dsct-adicional.png' },
  { texto: '+3% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/3-dsct-adicional.png' },
  { texto: 'Tu reserva vale x30', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x30.png' },
  { texto: '+1% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/1-dsct-adicional.png' },
  { texto: '$300 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/300-dscto-adicional.png' },
];

export const config: CampaignConfig = {
  title: 'Feria Virtual Menorca 2025 - Ruleta de Premios',
  description: 'Gira la ruleta y gana descuentos exclusivos en terrenos y viviendas.',
  heading: '¡Gira la ruleta y gana!',
  subheading: '¡La Feria Menorca volvió con descuentos IMPERDIBLES!\n¡No te lo pierdas!',
  fechaVigencia: 'Del 14 de Julio al 17 de Julio',
  bgImage: 'https://menorca.pe/wp-content/uploads/2025/07/ruleta-fiesta-patrias.jpg',
  ruletaImg: 'https://menorca.pe/wp-content/uploads/2025/06/ruleta_456.png',
  ganasteImg: 'https://menorca.pe/wp-content/uploads/2025/06/ganaste-ruleta.png',
  graciasImg: 'https://menorca.pe/wp-content/uploads/2025/06/gracias-por-participar.png',
  logoImg: 'https://menorca.pe/wp-content/uploads/2025/07/feria-virtual-4ta-edicion.png',
  pinImg: 'https://menorca.pe/wp-content/uploads/2025/06/pin-ruleta.svg',
  botonGiraImg: 'https://menorca.pe/wp-content/uploads/2025/06/gira-y-gana.png',
  sonidoUrl: '/sounds/sonido-ruleta-menorca.mp3',
  utmSource: 'ruleta-feria-virtual-2025',
  premios: premiosBase, // fallback global
  plazas: [
    {
      label: 'Arequipa',
      id: 41,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Carabayllo',
      id: 57,
      maxDiscount: 3000,
      premios: [
        { texto: 'Tu reserva vale x10', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x10.png' },
        { texto: '+2% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/2-dsct-adicional.png' },
        { texto: '+3% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/3-dsct-adicional.png' },
        { texto: '$300 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/300-dscto-adicional.png' },
        { texto: '+1% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/1-dsct-adicional.png' },
        { texto: '$500 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/500-dscto-adicional.png' },
        { texto: 'Tu reserva vale x20', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x20.png' },
        { texto: 'Tu reserva vale x30', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x30.png' },
      ],
    },
    {
      label: 'Cieneguilla',
      id: 12,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Chilca',
      id: 56,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Chiclayo - Posada del Sol',
      id: 52,
      maxDiscount: 3000,
      premios: [
        { texto: '+1% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/1-dsct-adicional.png' },
        { texto: '+2% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/2-dsct-adicional.png' },
        { texto: '+3% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/3-dsct-adicional.png' },
        { texto: '$300 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/300-dscto-adicional.png' },
        { texto: '$500 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/500-dscto-adicional.png' },
        { texto: 'Tu reserva vale x10', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x10.png' },
        { texto: 'Tu reserva vale x20', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x20.png' },
        { texto: 'Tu reserva vale x30', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x30.png' },
      ],
    },
    {
      label: 'Chiclayo - San Antonio',
      id: 68,
      maxDiscount: 3000,
      premios: [
        { texto: '+1% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/1-dsct-adicional.png' },
        { texto: '+2% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/2-dsct-adicional.png' },
        { texto: '+3% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/3-dsct-adicional.png' },
        { texto: '$300 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/300-dscto-adicional.png' },
        { texto: '$500 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/500-dscto-adicional.png' },
        { texto: 'Tu reserva vale x10', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x10.png' },
        { texto: 'Tu reserva vale x20', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x20.png' },
        { texto: 'Tu reserva vale x30', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x30.png' },
      ],
    },
    {
      label: 'Ica',
      id: 54,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Mala',
      id: 31,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Pachacamac',
      id: 30,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Piura',
      id: 36,
      maxDiscount: 3000,
      premios: [
        { texto: '+1% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/1-dsct-adicional.png' },
        { texto: '+2% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/2-dsct-adicional.png' },
        { texto: '+3% de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/3-dsct-adicional.png' },
        { texto: '$300 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/300-dscto-adicional.png' },
        { texto: '$500 de Dsct. adicional', img: 'https://menorca.pe/wp-content/uploads/2025/06/500-dscto-adicional.png' },
        { texto: 'Tu reserva vale x10', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x10.png' },
        { texto: 'Tu reserva vale x20', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x20.png' },
        { texto: 'Tu reserva vale x30', img: 'https://menorca.pe/wp-content/uploads/2025/06/reserva-x30.png' },
      ],
    },
    {
      label: 'Pisco',
      id: 59,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Punta Hermosa',
      id: 58,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Punta Rocas',
      id: 65,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Pucusana',
      id: 70,
      maxDiscount: 5000,
      premios: premiosBase,
    },
    {
      label: 'Chorrillos',
      id: 69,
      maxDiscount: 5000,
      premios: premiosBase,
    },
  ],
};
